name: Auto add issues to consensus branch

on:
  issues:
    types: [opened]

jobs:
  add-issue-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Create file from issue
        run: |
          ISSUE_ID=${{ github.event.issue.number }}
          ISSUE_BODY=${{ github.event.issue.body }}
          ISSUE_TITLE=${{ github.event.issue.title }}
          mkdir -p txs
          echo -e "Title: $ISSUE_BODY" > "txs/tx_$ISSUE_ID.md"

      - name: Commit and push to consensus branch
        run: |
          git checkout consensus || git checkout -b consensus
          git add txs/tx_*.md
          git commit -m "Add issue #${{ github.event.issue.number }}"
          git push origin consensus

